### ISSUE TITLE
can i publish ros msg type?

### ISSUE THREAD

**Issue by kimwin2** [ppianpak/rosbridgecpp#1]
HI really appreciate your affort to make this good sw.
I have a question that can i publish ros msg type?

I mean in this code below:

  rapidjson::Document d;
  d.SetObject();
  d.AddMember("data", msg, d.GetAllocator());

i have error when i put msg which is ros msg type.

is there any way to publish ros msg?

**Comment by ppianpak** [comment]
Hi there.
I don't understand what you're trying to do.
Could you try rephrasing or giving me some examples?

**Comment by kimwin2** [comment]
At the first time, thanks for your reply. 
I want to publish customized ROS message.
For example, I have A.msg which is written below:
```
---------------
A.msg
uint32 B
uint32 C
--------------
also B.msg is written below:
--------------
B.msg
uint32 D
A[] temp
---------------

```
Is there any way to publish B.msg using your rosbridgecpp? 
I finally know the way to publish A.msg, But yet I don't know how to publish B.msg.
I tried lots of ways to solve this problem. But I failed.

I will wait for your reply :)
thanks.

**Comment by ppianpak** [comment]
Of course yes.
You will need to make a json array of A named temp, which could look like this (supposed temp has 2 members):  [{"B":1,"C":1}, {"id":2,"C":1}].
An example of B message may look like this: {"D":1,"temp":[{"B":1,"C":1}, {"id":2,"C":1}]}.
You may need to check rapidjson document on how to manipulate an array of objects.

**Comment by kimwin2** [comment]
thanks.
I solved the problem.
