### ISSUE TITLE
Help needed in the HPP file

### ISSUE THREAD

**Issue by shikharvaish28** [ppianpak/rosbridgecpp#3]
I have a ROS system which I am planning to migrate to ROS2 using this bridge. I have declared some variables in the `header file`. How do I convert these variables ROS2. My code inside the `hpp` files looks something like this:

```hpp
        private:
            // ROS
            ros::NodeHandle                 nh;
            ros::NodeHandle                 nhPriv;
            ros::Time                       t;

            ros::Subscriber                 odomSub;
            ros::Subscriber                 imuSub;
            ros::Subscriber                 poseSub;

            ros::Publisher                  filterPub;
```

**Comment by ppianpak** [comment]
I have never checked what needs to be changed to migrate into ROS2.
It would be helpful if you tell me more about the changes or give me a link.

That aside, I don't think you are supposed to use ROS' structures (e.g., Nodehandle, Time, Subscriber, Publisher) inside the hpp file as the bridge library is intended to be used on non-ROS applications (standard C++11 applications in this case).

**Comment by shikharvaish28** [comment]
> the bridge library is intended to be used on non-ROS applications 

Do you mean to say that I can' t use it to port my existing ROS application?

**Comment by ppianpak** [comment]
Why would you need to port a ROS application when it's already a part of ROS ecosystem?
The library is for C++11 non-ROS applications to communicate with ROS system.
That's why you don't see any ROS structures in my code, just websocket and json.

**Comment by shikharvaish28** [comment]
I want to port it from ROS 1 to ROS 2 in order to compare the performance.

**Comment by ppianpak** [comment]
If you want to compare the performance of ROS and ROS2, why don't you just use them by themselves without rosbridge?

**Comment by shikharvaish28** [comment]
It's a really long story. BTW thanks for the help.

**Comment by ppianpak** [comment]
I'm not sure what you want to do here, hopefully you can figure it out.
