### ISSUE TITLE
boost update depracated get_io_service

### ISSUE THREAD

**Issue by argo-1** [ppianpak/rosbridgecpp#4]
Hello. Thank you for publishing this repo!

Would it be possible to find out which version of Boost you were running? get_io_service(), used in client_ws.hpp, was recently depracated

**Comment by argo-1** [comment]
Sorry, I just realized this is part of the Simple-Websocket-Server repo, which has received many updates from the publisher, as compared to the version used here.  (https://gitlab.com/eidheim/Simple-WebSocket-Server) Is this repo also planned to be updated accordingly?

**Comment by ppianpak** [comment]
I have the plan to update this repo soon. Hang in there buddy.

**Comment by ppianpak** [comment]
I've updated the repo.

**Comment by argo-1** [comment]
Thank you very much for the quick update!!
